### ISSUE TITLE
Clear error message 

### ISSUE THREAD

**Issue by Chrisvann1** [augustus-thomas/noteworthy#27]
Input the filename you want to clear: Science
Traceback (most recent call last):
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/Frontend.py", line 254, in <module>
    Introduction()
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/Frontend.py", line 251, in Introduction
    main()
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/Frontend.py", line 231, in main
    ClearNotes()
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/Frontend.py", line 160, in ClearNotes
    check_for_file = backend.del_file_contents(file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/backend.py", line 97, in del_file_contents
    save_modified(file, date = format_date(date.today()))
  File "/Users/chrisvann1/Desktop/Software Development/Project1/noteworthy/backend.py", line 20, in save_modified
    f.write(str(date) + chr(0x1F) + "," + file + '\n')
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "_io.TextIOWrapper") to str

**Comment by tferrelCOW** [comment]
Clear currently works for me.
